package be.cegeka.domain.entity.highscore.testbuilders;

import be.cegeka.domain.entity.highscore.Highscore;
import be.cegeka.domain.entity.highscore.User;

public class HighscoreTestBuilder {

    // Default the id is not set.
    // Integration test will have an id generated by the repository
    private long id;
    private float highscore = 9001;
    private User user = UserTestBuilder.aUser().build();

    public static HighscoreTestBuilder aHighscore() {
        return new HighscoreTestBuilder();
    }

    public Highscore build() {
        return  Highscore.HighscoreBuilder.highscore()
                .withId(id)
                .withHighscore(this.highscore)
                .withUser(user)
                .build();
    }

    public HighscoreTestBuilder withId(long id) {
        this.id = id;
        return this;
    }

    public HighscoreTestBuilder withHighscore(float highscore) {
        this.highscore = highscore;
        return this;
    }

    public HighscoreTestBuilder withUser(User user) {
        this.user = user;
        return this;
    }

    public HighscoreTestBuilder withoutUser() {
        this.user = null;
        return this;
    }
}